title: Default Page
icon: alert

columns:
  main:
    width: 1/2
    sections:
      fields:
        type: fields
        fields:
          defaultHeadline:
            label: Error page
            type: headline
          defaultTitle:
            label: Title
            type: text
            required: true
          defaultParagraph:
            label: Paragraph
            type: writer
            inline: true
            required: true