name: Services
icon: cog
label: "| {{ servicestitle }}"
fields:
  servicesHeadline:
    label: Services
    type: headline
    numbered: false
  servicesLabel:
    label: Label
    type: text
  servicesTitle:
    label: Title
    type: text
    required: true
  services:
    label: Services
    type: structure
    required: true
    columns:
      title:
        width: 1/4
      paragraph:
        width: 2/4
      destination:
        width: 1/4
    fields:
      title:
        label: Title
        type: text
        width: 2/3
        required: true
      isHighlighted:
        label: Is highlighted?
        type: toggle
        width: 1/3
        text:
          - "no"
          - "yes"
      paragraph:
        label: Paragraph
        type: writer
        inline: true
        required: true
      destination:
        label: Destination page
        type: pages
        max: 1
        image: icon