title: Site

tabs:
  menu:
    icon: dashboard

    columns:
      left:
        width: 1/3
        sections:
          content:
            type: fields
            fields:
              pagesHeadline:
                label: Pages
                type: headline
                numbered: false
          listed:
            headline: Listed pages
            type: pages
            status: listed
            image: icon
          unlisted:
            headline: Unlisted pages
            type: pages
            status: unlisted
            image: icon
          drafts:
            headline: Pages in draft
            type: pages
            status: draft
            image: icon

      right:
        width: 2/3
        fields:
          navigationBlockHeadline:
            label: Navigation
            type: headline
            numbered: false
          navigationBlock:
            label: Navigation block
            type: blocks
            required: true
            max: 1
            fieldsets:
              - navigation
          lineA:
            type: line
          
          logosHeadline:
            label: Logos
            type: headline
            numbered: false
          logoLight:
            label: Logo light
            type: files
            multiple: false
            required: true
            layout: cards
            width: 1/2
            image:
              back: "#FFFFFF"
          logoDark:
            label: Logo dark
            type: files
            multiple: false
            required: true
            layout: cards
            width: 1/2
            image:
              back: "#40484F"



  contact:
    icon: phone

    columns:
      left:
        width: 1/3
        fields:
          contactHeadline:
            label: Contact info & social media
            type: headline
            numbered: false
        
      right:
        width: 2/3
        fields:
          contactInfoHeadline:
            label: Contact info
            type: headline
          email:
            label: Email
            type: email
            width: 1/2
            required: true
          phone:
            label: Phone
            type: tel
            width: 1/2
            required: true
          lineB:
            type: line
          socialsHeadline:
            label: Social media
            type: headline
          socials:
            extends: fields/socials



  footer:
    icon: grid-bottom

    columns:
      - width: 1/4
        fields:
          gap-a:
            type: gap
      - width: 1/2
        fields:
          footerBlockHeadline:
            label: Footer
            type: headline
            numbered: false
          footerBlock:
            label: Footer block
            type: blocks
            required: true
            max: 1
            fieldsets:
              - footer
      - width: 1/4
        fields:
          gap-b:
            type: gap
      



  metaInformation:
    extends: fields/metaInformation